- packages.json
[**nim-csfml**](https://github.com/BlaXpirit/nim-csfml): Nim Bindings for Simple and Fast Multimedia Library (through CSFML)
> Add "csfml"

- packages.json
Reference to the package "parsetoml" (@GitHub) added.
> New package "parsetoml" added to the list

- packages.json
https://github.com/docopt/docopt.nim
> Add "docopt", update location of "random"

- packages.json
I added another library I've been using for a while; the documentation is [here](http://vision.caltech.edu/~mmcgill/tuples.html).
> Added tuples library

- packages.json
it's a rational arithmetic module
> nimrat added

- packages.json
I renamed the NimQML to nimqml
> Fixed NimQML renaming to nimqml

- packages.json
Signed-off-by: Akira Hayakawa <ruby.wktk@gmail.com>
> Add msgpack

- packages.json
Would love to have beastalkd.nim included in the nimble index. If you want to provide any feedback on the module as well (I'm learning the language), that would be a great bonus :)
Btw, I tried running `nible build` in my root, but nothing happened. I can find no documentation on this, so I basically haven't verified the .nimble file. Should be ok though.
> Beanstalkd

- packages.json
Adds my packages for Qt 5's Qt SQL library and OrientDB.
> Add packages I've created recently.

- packages.json
generate PDF file programmatically, written in nim
> add nimPDF package

- packages.json
https://github.com/megawac/RingBuffer.nim
> Add RingBuffer package

- packages.json
Personal libshout wrapper used in one of my projects.
Someone might find it usefull
> Added nshout - libshout bindings

- packages.json
LLVM bindings for the Nim language
> Add LLVM package

- packages.json
Added a Nim source only UUID generator library
> Added library nuuid

- packages.json
> Fixed a typo.

- packages.json
msgpack4nim is another MessagePack implementation written in pure nim
> add msgpack4nim package

- packages.json
See https://github.com/apense/shimsham. At version 0.1.0-alpha
> Added ShimSham to the list

- packages.json
renamed nim-heap to binaryheap and nim-stringinterpolation to stringinterpolation
> libs renamed; libovr added

- packages.json
Simple package for query HTML/XML elements using a CSS3 or jQuery-like selector syntax
> add q package

- packages.json
I also updated the gmp's url and web as @jovial kindly transferred his repository to me.
> Add bignum package

- package_scanner.nim
- package_scanner.nim was not checking for "tags" even though "tags" are required per https://github.com/nim-lang/packages#adding-your-own-package so that was fixed
- A package with a missing name and other errors counted as 1 error,
while a package with a missing description and a missing method for instance
counted as 2 errors. Strange. There are two possible approaches: count the total number of errors
or count the total number of erroneous packages. "Why count at all?" one could also argue :grin: .
I decided to count the number of erroneous packages.
- Refactored the checks for clarity of control flow
- :warning: `package_scanner` still does the "wrong" thing of checking for `web` url and not the real `url`. I have conceptual ideas, but I don't know how to implement them...yet!
- …
> improved(?) package_scanner!

- packages.json
Please accept my iterator library called "lazy" to be part of the nimble packages, or please indicate if changes are required.
> Added lazy library to packages.json

- packages.json
Small fuzzing system based on fauxfactory
> Added nimfuzz

- packages.json
> Added linalg

- packages.json
Some code of mine broke on 0.11.2 stable due to the rename. This fixes those problems.
> Add options

- packages.json
> Added memo package

- packages.json
Added patty, a pattern matching library
> Added patty

- packages.json
Einheit is a new unit testing module.
> Added einheit to the package.json.

- packages.json
Signed-off-by: rbmz <rbmz@users.noreply.github.com>
> added stopwatch

- packages.json
> Added csvtools

- packages.json
HttpForm, Http Request Form Parser.
> add httpform module

- packages.json
This module implements an asynchronous event loop which can distribute and callback **`asyncdispatch.Future`**. **`{.async.}`** is effective. 
It's expected to easy programming with **MVC**.
```nim
proc foo(e: Args) {.async, closure.} =
await sleepAsync(100)
echo e.req.userId
proc bar(e: Args) {.async, closure.} =
await sleepAsync(100)
echo "incoming"
var em = initAsyncEventTypeEmitter[Args]()
em.on("request", foo, bar)
```
> Add asyncevents module

- packages.json
crypto from nimPDF sister projects
> add nimSHA2 and nimAES packages

- packages.json
add everything search engine wrapper
> add everything search engine wrapper

- packages.json
extension modules for Nim's 'db_*' modules
> added 'nim-db-ex'

- packages.json
nimPDF's sister projects number 3 and 4, more to come
> add nimPNG and nimBMP

- packages.json
I would like to add LiteStore to the packages available on nimble.
> Added LiteStore.

- packages.json
Nim math library for sequences and nested sequences (extends math library)
> add seqmath package

- packages.json
> Revert "Added nimcat"

- packages.json
nimfp is the functional programming library. It introduces the types like List, Option, Stream, Either etc.
> Added nimfp library

- packages.json
unified single module combining db_sqlite, db_postgres, db_mysql
> add db package

- packages.json
glue code generator to bind Nim and Lua together using Nim's powerful
macro
> add nimLUA package

- packages.json
> Add entry for cligen.

- packages.json
> Added TeaFiles and Emmy

- packages.json
- capnp depends on collections
> add collections and Cap'n Proto implementation

- packages.json
> Added Rosencrantz

- packages.json
> Add a Stomp messaging library.

- packages.json
This is a library for xml documents building/manipulation in functional style
> Add xmltools library

- packages.json
This module implements an Docker Engine client based on Docker Remotet API. It's
asynchronous (non-blocking) that it can be used to write web services for deploying
swarm cluster and containers automatically on cloud environment. Of course, it
can also be used to write any local deployment tools.
> Add asyncdocker

- packages.json
> Added Python3 wrapper library

- packages.json
Adding the `progress` package, which provides a simple terminal status bar that can be used to improve the user interface of terminal based applications.
> Add package progress

- packages.json
Library for porting awk to nim
Apparently I did something wrong but I don't know what.
Update: forgot a comma in the json file
> Nim for awk programmers

- .travis.yml
Update to v0.13.0, v0.11.2 seems old.
> Update nim compiler on travis.

- packages.json
dotenv implementation for Nim. Loads environment variables from .env.
> Add package dotenv

- packages.json
Added a little wrapper over OpenCL and moved the BLAS bindings out of linalg
> Added nimcl and nimblas

- packages.json
Native Nim Zend API glue for easy PHP extension development.
> Added nimzend package.

- packages.json
Author of the old package agreed to remove it from `packages.json` and replace it with NimYAML:
https://github.com/nim-appkit/yaml/issues/1
> Replaced old yaml package with NimYAML

- packages.json
> Added spills

- packages.json
Also update licenses for my packages to BSD3.
> Add migrate package

- packages.json
A macro to kind of support "anonymous structures"
> Add subfield macro package

- packages.json
Add the semver package, this time manually rather than using `nimble publish`.
> Add `semver` package

- packages.json
@vegansk is the now the main maintainer of jnim
> jnim transfered to vegansk

- packages.json
Add library which allows to access Windows Registry without hassle.
> Add registry library

- packages.json
> Added BGFX wrapper

- packages.json
> Remove 'nim' and 'nimrod' tags.

- packages.json
Added a library containing a set of functions for creating games using Nim and SDL2.
> Added SDL gamelib

- packages.json
I am submitting a package for my new little programming language written in Nim, even though there is basically no documentation yet (but a comprehensive guide is planned and in progress).
> Added MiNiM package.

- packages.json
> Add libjwt

- packages.json
Simple gap buffer implementation backed by `seq[char]`s. Not much more to it, really.
> Add gapbuffer

- packages.json
I made a fork of rbmz's stopwatch library.  I asked him if he wanted to integrate any of the changes but I haven't heard back from him yet.
> Added my fork of stopwatch

- packages.json
I changed the scope of the stb_image wrapper I was working on to not include something the description says is.
> stb_image description change

- packages.json
Some methods imitating mutable sequences in scala etc.
> Added package mutableseqs

- packages.json
Add a wrapper for the linux framebuffer API.
> Add linuxfb, a wrapper for the Linux framebuffer API

- packages.json
This is a simple stemmer for Russian and English language, there is a possibility to add new languages by providing a set of rules. It is a simple implementation of the algorithms described at http://snowballstem.org
> simple stemmer

- packages.json
> Add HTML5 Canvas bindings

- packages.json
I'm probably going to start work on this next week, but I'd like to reserve the name right now.  It's going to be another light wrapper, this time over the `XMLHttpRequest` object.
> Ajax package

- packages.json
**NESM** is a tool for generating the serialization and deserialization code. Could be used for making network messages or files from objects and vise versa.
* nested structures (even declared in other module)
* object variants
* dynamic and static (when the structure size is constant and known at compile time, useful for UDP packets) modes
Documentation can be found [here](https://xomachine.github.io/NESM/).
I hope the Nim community will find it useful! =)
> Added NESM - Nim's Easy Serialization Macro

- packages.json
May I please request a pull request to merge the Nim dpdk bindings library to master branch. Thank you.
> Added dpdk

- packages.json
- add [snail](https://github.com/stisa/snail) ( linear algebra in nim and js )
- add [websockets](https://github.com/stisa/websockets) ( websockets for nim js )
> add snail and websockets

- packages.json
See https://github.com/nim-lang/packages/pull/479
> websockets->jswebsockets

- packages.json
> Added cello

- packages.json
Seems the github username has changed
> Renamed BlaXpirit to oprypin

- packages.json
I've added a new package called serializetools. Thanks in advance for the help.
> Added serializetools.

- packages.json
Hi Dom/All! Hope all is well!
I did some cleanup on my old package, including a name change, so here is  PR updating the path in nimble.
> Update package path for superfunc/{monad/maybe}

- packages.json
I added a currying library for Nim. Please check it.
> Add currying

- packages.json
Arraymancer is a tensor / multidimensional array library
> Add arraymancer

- packages.json
A nil coalescing operator `??` for Nim
> add coalesce

- packages.json
Added the persistent vectors implementation, gtkgenui for gtk2, and my little pcap reading library.
> Added three new packages

- packages.json
vkapi a wrapper for the vk.com API (russian social network)
https://github.com/cyberlis/nimvkapi
> vkapi a wrapper for the vk.com API (russian social network)

- packages.json
We've choosen to change address to my fork
> Change repository address

- packages.json
> nim-sndfile -> sndfile

- packages.json
I believe I've actually added the .nimble file. the issue was me being an idiot and forgetting to actually push the refs to my github repo.
> Added package libgit2

- packages.json
added multicast; procs to join and leave a multicast group
> added multicast

- packages.json
FYI I'm having to open this PR manually - hope this is all that's left to do.
```
Pushing to remote of fork.
Info Creating PR
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```
> Added package fugitive

- packages.json
Added my Design by Contract package (under development but seems to work fine).
> addded package contracts

- .travis.yml
- validate_json.js
Now you'll see this travis failure when packages.json is invalid ;) Restart travis after #592 is merged
> Validate json with js

- packages.json
> Added package httpauth

- packages.json
added nimates, a client library for the Postmates API
> added nimates

- packages.json
my timerpool implementation is ready 2 publish
> nimble entry for timerpool implementation

- packages.json
> Added package simpleAST

- packages.json
> Taking over jnim again

- packages.json
The database schema migration library
> Add `dbschema` library

- packages.json
file dialog, system file/folder icon, open file with default app
> Add os_files package

- packages.json
Adding [nimgen](https://github.com/genotrance/nimgen) to Nimble.
> Add nimgen

- packages.json
Added my new binary parser package
> Added binaryparse package

- packages.json
Added zhsh package for Zhang-Shasha tree edit distance algorithm
> Added zhsh (zhangshasha) package

- packages.json
Added a small terminal style library I've been using for various projects
> Added termstyle package

- packages.json
Reserving a cool name to sell it later for $1M.
> Added nimpy

- packages.json
Made some bindings for the p5 javascript library. Maybe someone finds them useful.
> added nimp5 to package.json

- packages.json
> typo, missing a "t" in clblast

- packages.json
> Register ttmath

- packages.json
Oops, nimble used the wrong URL. I'll fix that later today, sorry about that.
> Add package nimhdf5

- packages.json
Couldn't rebase as deleted the repo before merging
> Added package loopfusion (followup #687)

- packages.json
https://github.com/juancarlospaco/nim-random-font-color#nim-random-font-color
> Added package random_font_color

- packages.json
https://github.com/juancarlospaco/nim-bytes2human#nim-bytes2human
> Added package bytes2human

- packages.json
https://github.com/juancarlospaco/nim-crc32#nim-crc32
> Add package crc32

- packages.json
https://github.com/juancarlospaco/nim-datetime2human#nim-datetime2human
> Add package datetime2human

- packages.json
As requested, tiny packages merged on bigger one...
> Add package osutil

- packages.json
Hello,
I coded this module with helper functions for json marshal/unmarshal. To do things I could not with current json support.
Thanks!
> jdec module

- packages.json
A website management tool - [website creator](https://nimwc.org).
> Add package websitecreator

- packages.json
Please add shaname to packages.json.
> Added shaname.

- packages.json
Sorry to bother you again.
Web URL modified from "gttps://..." to "https://...". Please merge.
> Fixed shaname web URL.

- packages.json
See https://github.com/NimParsers/parsetoml/issues/12.
/cc @ziotom78
> Update parsetoml url

- packages.json
webterminal is a very VERY simple HTML5 Javascript library that let's a nim app do simply text in/out in a tty fashion.
> Added webterminal package

- packages.json
This adds the Fab package, useful for fancy text output in the terminal. Thanks for your time!
> Add fab package

- packages.json
This adds a package for validating Nim object fields using object field pragmas. Tested under 0.18.0. Thanks for your time.
> Add validation package

- packages.json
> Remove fractions package

- packages.json
> add nlopt library

- packages.json
Add nim7z, nimarchive, nimpcre and nimdeps to nimble packages.
> Add recent packages

- packages.json
https://github.com/juancarlospaco/nim-kdialog#nim-kdialog
Easy GUI for teaching Nim.
CI errors are from someone else.
> Add package kdialog

- packages.json
Is it normal for nimble publish to fail at the last step? I had to do this pull request manually
> Added package nimspice

- packages.json
API Client Lib for https://openexchangerates.org/account/app-ids
> Added package openexchangerates

- packages.json
I transferred the repository to an organization.
> Update the BN repo's URL.

- packages.json
Builds on top of Telebot, usable just editing `config.ini`, but can also use plugins just putting it on the `./plugins/` folders.
> Added package nim_telegram_bot

- packages.json
This Nim package includes proc's for working with Xiaomi devices.
You can interact with the Xiaomi devices in 3 ways:
1) **Read** - Asking for a status, e.g. is the door open (door sensor)
2) **Report** - Awaiting an action, e.g. when the door opens, it sends a notification (door sensor)
3) **Write** - Send a message to the device (only some devices accept this), e.g. play a sound on the gateway
All Xiaomi devices are connected to a gateway. It is through this gateway, we are communicating with each of the devices.
> Added xiaomi

- packages.json
(This package needs NiGui to use)
> Add package nmiline

- packages.json
WebP is like JPG but half the size!.
> Add package webp

- packages.json
bindings package for Mathematica/Wolfram's WSTP protocol for extending or embedding :)
> Added package wstp

- packages.json
A simple GUI front for Nimble.
https://github.com/ThomasTJdev/nim_nimble_gui
Please let me know, if you like to reserve the name nimblegui.
> Added nimblegui

- packages.json
GUI Automation for Linux, user interaction simulation, clicker, usability tests, etc.
> Added package xdo

- packages.json
[OpenStreetMap](https://openstreetmap.org) MultiSync Library, Example and CLI App.
:cat:
> Added package overpass

- packages.json
OpenStreetMap Nominatim API Lib, MultiSync.
> Added package nominatim

- packages.json
> Added package openstreetmap

- packages.json
Repo has been removed from github.
> Remove package monero

- packages.json
Free world wide Creative Commons & Open Data Licensed Weather data.
> Added package openweathermap

- packages.json
Nim Pastebin-like LAN-only Offline Playground Scratchpad Web thingy for teaching Nim on IRL events.
> Added package hackpad

- packages.json
Calibre ebooks app database client lib.
> Added package calibre

- packages.json
Fix psutil, point to new maintained fork, original author credits remain, an explanation is also added, 
author is not even active on github at all, if original author ever comes back with a maintained repo feel free to revert back,
no drama lama, I just want to see things working. All Tests pass Ok for `stable` and `devel`.
:cat:
> Fix psutil

- packages.json
Another CrossPlatform CrossDesktop Native GUI Toolkit for Nim.
> Added package tinyfiledialogs

- packages.json
This package is [https://github.com/ai/nanoid](nanoid), implemented in Nim.
> Add nanoid package

- packages.json
Ref:
- https://github.com/nim-lang/Nim/pull/9234
- https://github.com/nim-lang/graveyard/pull/1
> Add the xmldom and xmldomparser packages from graveyard

- packages.json
Ref: https://github.com/nim-lang/packages/issues/399#issuecomment-243021190
> Remove the unnecessary "nim" tags

- packages.json
my packages are outdated and unmaintained.
> unpublish nimcalcal, calendar

- packages.json
Converts Nim code to Markdown. Can convert a whole Nim file or a string with Nim code.
https://github.com/ThomasTJdev/nimtomd
> Add nimtomd

- packages.json
> Added package urlshortener

- packages.json
MultiSync Client for Open Data Gov Geo API https://georef-ar-api.readthedocs.io
> Add package georefar

- packages.json
1 huge proc to crosscompile Nim source code into several targets including Documentation (designed for Arch Linux on Docker).
> Added package crosscompile

- packages.json
Add sermon.
This program purpose is to monitor your system health and alert you if the specified levels are reached.
- used space
- free mem
- process state
- process mem
- url response codes
> Add sermon

- packages.json
MultiSync Client for Open Data Gov Geo API https://servicios.usig.buenosaires.gob.ar
> Add package usigar

- packages.json
API lib for http://project-osrm.org/docs/v5.7.0/api
> Added package osrm

- packages.json
MultiSync Client for Open Data Gov Time-Series API https://datosgobar.github.io/series-tiempo-ar-api
> Add package seriesdetiempoar

- packages.json
HTML & CSS Minifier Lib & App.
> Add package css_html_minify

- packages.json
> Add crap package

- packages.json
> Added package open_elevation

- packages.json
An argument parsing library with support for git-style sub commands.
> Add argparse

- packages.json
Add bgfxdotnim (BGFX C99 bindings)
> Add bgfxdotnim

- packages.json
> Add Gatabase

- packages.json
https://github.com/Matceporial/nim-urand
https://github.com/Matceporial/nim-timespec_get
> Add packages urand and timespec_get

- packages.json
see https://github.com/mattaylor/elvis
> Added 'elvis' package

- packages.json
MultiSync API Client for http://unsplash.com
> Added package unsplash

- packages.json
https://github.com/juancarlospaco/biblioteca-guarrilla#biblioteca-guarrilla
> Add package biblioteca_guarrilla

- packages.json
- [Steam](https://store.steampowered.com) MultiSync API Client.
> Added package steam

- packages.json
[itchio](https://itch.io) MultiSync API Client.
> Added package itchio

- packages.json
SQL builder for INSERT, UPDATE, SELECT and DELETE queries. The builder will check for NULL values and build a query with them.
> Add sqlbuilder

- package_scanner.nim
Change `nil` to `""` and `isNil` to `== ""`.
Also some quick style fixes (removing empty lines, mostly).
> no nil strings anymore

- packages.json
This depends on https://github.com/nim-lang/graveyard/pull/7 and shouldn't be merged before that one is merged.
> add four packages from graveyard

- packages.json
> Update packages previously under EmberCrypto to their new locations/names.

- packages.json
https://firejail.wordpress.com/features-3/#namespaces
> Added package firejail

- packages.json
> Update packages.json - Added nim-nmap

- packages.json
https://libravatar.org Lib & App, Gravatar alternative.
> Added package libravatar

- packages.json
> Added package html_tools

- packages.json
> Update packages.json with my package

- packages.json
https://github.com/2vg/mofuw has been archived
> Flag mofuw as abandoned

- packages.json
Adding [matplotnim](https://github.com/ruivieira/matplotnim).
> Add matplotnim

- packages.json
Added a RPC framework I've been working on for a while.
> Added nerve rpc framework

- packages.json
Greetings!
I'd like my package to be added, thank you.
> Added package "validateip"

- packages.json
- Lightweight Contract Programming.
> Added package contra

- packages.json
A javascript wrapper library for working with [D3](https://d3js.org).
> Add d3 ffi library

- packages.json
closes #1127
closes #1128
closes #1129
closes #1130
closes #1131
closes #1132
closes #1135
closes #1136
closes #1137
closes #1138
> add all packages that were on hold at once

- packages.json
First package on Nimble, let's hope it works 😄
> add NumericalNim to Nimble

- packages.json
> Added package sweetanitify

- packages.json
math float func that makes floats bounce.
> Add package easings

- packages.json
Provides the Fletcher checksum algorithm as a Nim module.
> Adding fletcher package

- packages.json
- Euclidean Division.
- Euclidean Modulo.
> Add package euclidean

- packages.json
At the moment Linux-only, but ambitions are for BSD sometime.
> Add `procs` library+CLI

- packages.json
`nimga` is the Genetic Algorithm Library.
> Added package nimga

- packages.json
> add package htmlview

- packages.json
closes #1179, #1180, #1181, #1182, #1183
> add all new packages at once

- packages.json
Added bearssl package. Lost of copypaste from Araq's lib with small fixes. Hope you don't mind @Araq.
> Added bearssl package

- packages.json
I will be removing my Nimble repositories from Github.
> Move packages of ehmry to git.sr.ht

- packages.json
I'd like to add my oracle wrapper - the API is functional now
> oracle odpic-wrapper

- packages.json
tsv2json is a terminal utility written entirely in Nim. It takes a file or stream with a TSV header and zero or more TSV records and returns the same information, formatted as JSON.
> Added package tsv2json

- packages.json
> Add leveldb bindings

- packages.json
jit-ed or not, the correct name should be "evmc".
> rename evmjit to evmc

- packages.json
Pls review to add new package gdbmc
> add package gdbmc

- packages.json
Sorry.
package description was default.
I changed it.
> Update description of faker

- packages.json
https://github.com/dom96/choosenim/issues/56
> Added package choosenim

- packages.json
Just found this old package, which apparently was part of the stdlib years ago. Since @lcrees archived his repository, I'd take over if that's ok.
> update `polynumeric` to a working state

- packages.json
backed by tests, fuzzing, benchmarks via CI on the repo.
> Add package nbaser

- packages.json
> Add package shizuka

- packages.json
Create SVG-files with QR-codes from strings.
https://github.com/ThomasTJdev/nim_qr
```nim
import qr
qrSvgFile("https://forum.nim-lang.org", "test.svg")
```
> Add qr package

- packages.json
Luhn's Algorithm implementation in Nim
> Added package luhny

- packages.json
nimwebp - webp encoder and decoder bindings
> add nimwebp package

- packages.json
{
"name": "zfcore",
"url": "https://github.com/zendbit/nim.zfcore",
"method": "git",
"tags": [
"web",
"http",
"framework",
"api",
"asynchttpserver"
],
"description": "zfcore is high performance asynchttpserver and web framework for nim lang",
"license": "BSD",
"web": "https://github.com/zendbit/nim.zfcore"
}
> add zfcore nimble package

- packages.json
add zfblast nimble package
{
"name": "zfblast",
"url": "https://github.com/zendbit/nim.zfblast",
"method": "git",
"tags": [
"web",
"http",
"server",
"asynchttpserver"
],
"description": "High performance http server (https://tools.ietf.org/html/rfc2616) with persistent connection for nim language.",
"license": "BSD",
"web": "https://github.com/zendbit/nim.zfblast"
}
> add zfblast nimble package

- packages.json
Hello,
this is my first nim package. Any feedback is highly welcome!
> Add package roots

- packages.json
This is my first package, if there's anything wrong let me know and I'll do my best to fix it. 
Thank you!
> Add filesize package

- packages.json
Automated Bug Reporting for Nim, example https://github.com/juancarlospaco/nimbug/issues/1#issue-585491959
> Add package nimbug

- packages.json
This is an API for the website www.eloverblik.dk, which collects energy usage from Danish energy companies.
You use this as a library, which you import, or you can run it as a binary. It'll get your energy usage, format it to JSON, and sends the data with MQTT.
> Add eloverblik

- packages.json
https://github.com/Yardanico/nim-libvlc
> Add package libvlc

- packages.json
This closes #1422, #1423, #1424, #1425, #1427.
> add multiple packages

- packages.json
Moved from AndreiRegiani/INim -> inim-repl/INim
> Updated INim, moved to organization account

- packages.json
Added [darwin](https://github.com/yglukhov/darwin)
> Added darwin package

- packages.json
A simple GUI for choosenim with [webgui](https://juancarlospaco.github.io/webgui/).
Repo: [choosenimgui](https://github.com/ThomasTJdev/choosenim_gui)
> Added choosenimgui

- packages.json
A bit too tiny to be a package for my liking, but people in https://forum.nim-lang.org/t/1305 asked :P
> Add package strenc

- packages.json
> Add package trick

- packages.json
> Add package wAuto

- packages.json
```nim
import nimtm
let connection = initQb("http://127.0.0.1:8080", "admin", "adminadmin")
conn.login()
if conn.connected:
var torrents = conn.getTorrents()
for torrent in torrents:
echo getTorrentFiles(torrent["hash"])
```
> added nimqt

- packages.json
Adding a 128-bit decimal library to nimble.
> Add decimal128

- packages.json
> Added package datetime_parse

- packages.json
> Add fusion package

- packages.json
> add package taskqueue and threadproxy

- packages.json
See https://github.com/molnarmark/spinny/pull/8#issuecomment-635283926 for the author agreement.
> Take over Spinny package

- packages.json
Remove empty tag because it looks ugly in the nimble directory :)
> Remove empty tag from simplediff

- packages.json
specifically:
1. username changed
2. relicensed (MIT -> Unlicense)
> update pipe package metadata

- packages.json
Improving [on a recent hack](https://forum.nim-lang.org/t/6403) here is my first nimble package, a small glue wrapper to make text processing more convenient with Nim by making it look vaguely familiar to those with awk experience.
> naw, awk-style nim processing for nim

- packages.json
Trying to see if this works, unlike #1517
> add gerbil

- packages.json
This is my first time publishing a Nim package :) not fully complete but gonna keep expanding it with other niceties 🚀
> Add package iridium

- packages.json
Library for attaching files to emails.
> Add nimMime

- packages.json
Should I rename this to something else?
Because I found this:
> Add package vds

- packages.json
This is the plugins for the zfcore framework https://github.com/zendbit/nim.zfcore
> add zfplugs plugins for the zfcore framework

- packages.json
Add a little port of Python difflib and hldiff example program.
> Add hldiff

- packages.json
i didn't forget a comma this time o(_ _)o
> (/・・)ノ add ms

- packages.json
Add a numpy like ndarray and dataframe library for nim-lang : numnim
https://github.com/YesDrX/numnim
> numnim: a ndarray library

- packages.json
Adds the geometryutils package
> Add geometryutils library

- packages.json
Simple watchdog (watch file changes modified, deleted, created) in nim lang.
> add nim watchdog package

- packages.json
Add randgen a random variable generation lib
> Add randgen a random variable generation lib

- packages.json
Project now has multi-producer and multi-consumer queues.
> lockfreequeues: update tags, description, and doc link

- packages.json
Several libraries related to audio that i am working on.
> Add audio libraries

- packages.json
Renamed package to correct spelling error (opentrivadb --> opentdb)
Added docs
> Updated package details

- packages.json
This is my version of the tor library for nim. I believe it will be useful for nim-lang on the tor network.
> Added torim package

- packages.json
Higher-level bindings for libclang in nim. 
https://github.com/haxscramper/hcparse
https://haxscramper.github.io/hcparse-doc/src/hcparse/libclang.html
> Add package hcparse

- packages.json
User-friendly wrapper for entity declarations in nim ast
> Add package hnimast

- packages.json
Adds the package[once](https://git.sr.ht/~euantorano/once.nim).
> Add package once

- packages.json
Added entry on package.json to nimchromepath. nimchromepath gets the chrome path(s) on Windows and *Nix Systems
> added nimchromepath to package.json

- packages.json
I removed nimble support for my package. No point to still list it here.
> remove fancylg

- packages.json
pure Nim declarative packes system for serializing/deserializing
> Added packets

- packages.json
Hello, 
I would like add my fpn library to nimble.
Thanks
> Add fpn library. A fixed point number library in pure Nim.

- packages.json
@Martinsos, for reference.
* https://github.com/Martinsos/edlib
> Add package edlib

- packages.json
Changed License from GPL-3.0 to MIT
> Changed psutilim License

- packages.json
The `nimble publish` command failed at the PR-creating part so I'm submitting this manually, hope that's ok...
> Added package classes

- packages.json
Api Calls for Ford vehicles equipped with the fordpass app.
> Add package ffpass

- packages.json
Refers to https://github.com/Cirru/ternary-tree .
> add ternary-tree

- packages.json
> Add geminim

- packages.json
> Add quickcrypt

- packages.json
> Add couchdb

- packages.json
> Add minhook package

- packages.json
I'm up for using another name if this is too generic. The previous name was "definesugar" which I didn't like very much
> Add package defines

- packages.json
Create ICS files for email invites, eg. invite.ics
> Add nimics (ics-file)

- packages.json
add stdext package
https://github.com/zendbit/nim.stdext
> add stdext

- packages.json
AccurateSums is a library containing algorithms to offers robust/accurate numerical methods to sum (and product) float.
Follow-up https://github.com/nim-lang/Nim/pull/16004
> Add accuratesums

- packages.json
See discussion: https://forum.nim-lang.org/t/7216
> Rename package to bingo

- .github/workflows/test.yml
- package_scanner.nim
If you want to switch to GitHub Actions for running checks, this seems to work (and doesn't hit the GitHub rate limits): https://github.com/iffy/packages/runs/1525986310?check_suite_focus=true
> GitHub actions

- packages.json
Compiled and wrapped tree-sitter grammars
> Add package htsparse

- packages.json
Wanted video for nimx so wrapped 3 video related packages to achieve nim playback support for av1/webm/opus audio files, the latest and greatest in open media
> Add 3 video related packages

- packages.json
This is my first Nim library, please feel free to make suggestions.
> Added azure_translate

- packages.json
I created a new account on github for my nim projects (this one), I moved torm and added a new project under the account enimatek-nl
> updated torm and added tencil

- packages.json
Sorry, I had to move all repositories to my personal namespace
> Updated links

- packages.json
ducominer is a fast, multithreaded miner for DuinoCoin written in Nim.
> Added package ducominer

- packages.json
Fork of [binaryparse](https://github.com/PMunch/binaryparse).
> Add package binarylang

- packages.json
A package for bioinformatic related algorithms and datastructures
> Added bionim

- packages.json
https://github.com/YesDrX/onnxruntime-nim
> onnxruntime c api for nim

- packages.json
https://github.com/YesDrX/gsl-nim
> gsl wrapper for nim

- packages.json
Convert json to xml  : JsonNode( compatible with  module json ) To  XmlNode (compatible with  module  xmltree)
> add json2xml package

- packages.json
> add package suru

- packages.json
Just source updates to my libraries since Bitbucket dropped Mercurial support.
> Update bitbucket sources.

- packages.json
A parser for Jupyter notebooks (https://github.com/ruivieira/nim-holst)
> Add holst package

- packages.json
> Add package aria

- packages.json
Add libsaedea:
Nim Library implementing a variation of Simple And Efficient Data Encryption Algorithm
Research paper pdf: INTERNATIONAL JOURNAL OF SCIENTIFIC & TECHNOLOGY RESEARCH VOLUME 8, ISSUE 12, DECEMBER 2019 ISSN 2277-8616 from IJSTR.org
> Add package libsaedea

- packages.json
Package to simplify RPC.
Call remote Nim functions as if it's local.
> Added 'nodem' package

- packages.json
Ref https://github.com/nim-lang/Nim/pull/17765#issuecomment-822019094
> update the jstin link

- packages.json
Memlib - Load Windows DLL from memory
> Add memlib

- packages.json
Change links to transfered libs
> Transfer Rainbow and Pine

- packages.json
> Add winimx package

- packages.json
> add expander

- packages.json
Also tweak the tags on my CBOR library for consistency.
https://git.sr.ht/~ehmry/preserves-nim
https://preserves.gitlab.io/preserves/
> Added package Preserves

- packages.json
nimble fork, handle requires in task and pre test
> Add package slim

- packages.json
> Add documentation to package listenbrainz

- packages.json
https://discord.com/channels/371759389889003530/755344160592101389/857654680892211240
> bignum is now transferred to SciNim GitHub org

- packages.json
> Add package syndicate

- packages.json
Amazon Simple Storage Service (AWS S3) basic API support.
* presigned url
* deleteObject
* headObject
* getObject
* putObject
* copyObject(s)
* moveObject(s)
> Add "awsS3"

- packages.json
Repository: https://github.com/ruivieira/nim-todoist
Documentation: https://ruivieira.github.io/nim-todoist/index.html
> Add nim-todoist

- packages.json
See FedericoCeratto/nim-package-directory#35
> Update nimflux tags, point to github

- packages.json
resolution nimble making use of system resolver
> Add resolv.nim

- packages.json
Morepretty - Does more than nimpretty.
> Add morepretty tool.

- packages.json
The original project is abandoned as far as I can tell, I submitted issues / PRs months ago with no reply, so I forked and improved it. If this needs to be submitted in a different way, let me know.
> Update `lastfm` package to reflect fork

- packages.json
Signed-off-by: David Krause <krause@biochem2.uni-frankfurt.de>
> added nimja https://github.com/enthus1ast/nimja

- packages.json
> Add unix crypt module

- packages.json
The repo has been deleted by Bitbucket, so the package can't be installed or fixed.
> Remove storage.

- packages.json
> Added package Loony

- packages.json
https://github.com/zendbit/nim.zfdbms
> add zfdbms to nimble directory package

- packages.json
I am not the author of zfdbms and taking description from About section of GitHub: https://github.com/zendbit/nim.zfdbms
This PR is to fix a broken nimble search and nimble list: https://github.com/nim-lang/nimble/issues/947
cc @zendbit
> add description to zfdbms

- package_scanner.nim
- packages.json
> add check for empty description

- .github/workflows/test.yml
Ref https://github.com/nim-lang/packages/pull/2019
Ref https://github.com/nim-lang/packages/pull/2018
Ref https://github.com/iffy/install-nim/issues/14
> upgrade install-nim

- packages.json
Exprgrad is an experimental deep learning framework for Nim based on a differentiable array programming language.
> Add package exprgrad

- packages.json
Converts a file with Jester routes to Swagger JSON which can be imported in Postman.
**jester => swagger => postman**
> Add jester2swagger

- packages.json
Adds Riimut package for transforming latin letters to futhark runes, or runes to latin text.
> Add Riimut package

- packages.json
I will change my Github username as soon as this is merged.
> Change Github username (Knaque -> tonogram)

- packages.json
I also edited my other project's git URL because it is now in its own org.
> Add wavecore

- packages.json
Correct spelling for description of Weave.
> Correct spelling

- packages.json
Add package for converting ogham scriptures to latin text, or vice versa.
> Add Ogham package

- packages.json
> Add package honeycomb

- packages.json
Noticed a typo in the description of a package I recently publised
> Fix typo in description

- packages.json
Problem with the current user name to close to my current job.
No problem to other projects because nobody use my work :)
> Change username to resolve name problem

- packages.json
Pure Nim implementation of the User Agent Parser (based on uap-core regexes).
> Add uap package

- packages.json
Alternative to the other zstd bindings.
> Add RemiZstd package.

- packages.json
Owlkettle is a declarative user interface framework based on GTK.
> Add owlkettle

- packages.json
https://github.com/theAkito/userdef
> Add userdef

- packages.json
https://github.com/theAkito/nim-useradd
> Add useradd

- packages.json
`ruby` provides bindings to the Ruby C API, and a high-level framework for embedding Ruby inside of Nim.
> Add Ruby Library

- packages.json
i hope the file i modified isnt malformed. i'm bad at json
> add `nimmikudance`

- packages.json
> Added nim_tinyfiledialogs package

- packages.json
> Fixed tinyfiledialogs name conflict

- packages.json
Hiya,
If the name is too generic I can think of something fancier to call it.
> Add rpgsheet

- packages.json
nimFF is a farbfeld image format encoder and decoder.
> Added nimFF

- package_scanner.nim
REF https://spdx.org/licenses/GPL-2.0-only.html
ref #2264
> add gpl-2.0-only; ref #2264

- packages.json
i recently created a library with a few functions scraping weather data from wttr.in, this is very useful because it does not require an open weather map api key
> add library wttrin

- packages.json
Let me know if name is too short or ambiguous
> Add package nage

- packages.json
I moved all my projects from gitlab to github because github have more users
> Moved my packages from gitlab.com/lurlo to github.com/thisago

- packages.json
Mersal, a wrapper for TextBelt's public API
> Add Mersal Package

- packages.json
- see https://github.com/nim-lang/nimble/pull/1017 and https://github.com/nim-lang/Nim/pull/20179
> Rename compiler to nim

- packages.json
Add two new packages, one is autotemplate, the other is deriveables.
> Add autotemplate and deriveables

- packages.json
Wrapper over the getdns API
https://git.sr.ht/~ehmry/getdns-nim
https://getdnsapi.net/
> Add package getdns

- packages.json
- Changed the url of my repos to my own git server
- Added `checkif` package
> Moved all my repos to my own git server; Added `checkif` package

- packages.json
I am currently cleaning up the exprgrad repository in preparation for NimConf and wanted to extract this module into a separate package.
> Add geometrymath

- packages.json
fixes https://github.com/nim-lang/packages/issues/2115
> correct package names

- packages.json
> remove package arbitrary

- packages.json
> Edit package nimem

- config.nims
- package_scanner.nim
- packages.json
> Empty tags now count as errors + removed empty tags from the packages list

- packages.json
Rename git repos due to a username change on github.
> Update packages.json (Username change thus changed the git repos of the packages)

- packages.json
ref https://github.com/nim-lang/Nim/pull/20951
> Add cgi0200

- packages.json
ref https://github.com/nim-lang/punycode
> Add punycode0933

- packages.json
> Add package strides

- packages.json
> Add tinyre

- packages.json
...
```nim
import
std/json,
openai
let resp = aiPrompt(apiKey, "Why is Nim-lang the best programming language?", maxTokens = 100)
echo resp["choices"][0]["text"]
```
> Add package with basic api for openai

- packages.json
Release couchdbapi package v0.0.1
> Update packages.json - Add package couchdbapi v0.0.1

- packages.json
https://git.sr.ht/~ehmry/freedesktop_org
> Add freedesktop_org library

- packages.json
https://codeberg.org/eris/coap-nim
> Add taps-coap library

- packages.json
Nim REST client to Vikunja (https://vikunja.io/).
> Add nim-vikunja

- packages.json
Simple ORM for SQLite that can perform CRUD operations
https://github.com/ire4ever1190/ponairi
> Add ponairi

- packages.json
A simple library with a simple interface to do password hashing and validation with different algorithms
https://github.com/PhilippMDoerner/nimword
> Add package nimword

- packages.json
Playdate Nim bindings with extra features.
https://github.com/samdze/playdate-nim
> Add package playdate

- packages.json
Added my package - Nemini, a Gemini server
> Added Nemini

- packages.json
update my github project url not working correctly when using nimble if the name contain '.' char
> update my github project url

- packages.json
Router for Karax frontend framework.
https://github.com/moigagoo/kraut
> Add package kraut

- packages.json
> Mark package inumon as abandoned

- packages.json
> Fix url for psutilim

- packages.json
A collection of small templates and macros that aid in limiting the scope of mutable `var`iables as much as practical.
> Add package letUtils

- packages.json
Scaffolder for Karax.
https://github.com/moigagoo/sauer
> Add package sauer

- packages.json
Like `std/asyncmacro` but for iterators, not for procs. Works with `asyncdispatch`; compatibility with `chronos` is work in progress.
> Add package asyncIters

- packages.json
Package implementing dhash algorithm used for image de-duplication
> Add package dhash

- packages.json
A simple wrapper around the winapi to control the clipboard
https://github.com/4zv4l/nclip
> Add package nclip

- packages.json
> update minicoro URL

- packages.json
might be an unwanted child. But still a child.
> Add package nimpretty_t

- packages.json
tiny graphics lib
https://github.com/Angluca/tigr-nim
> Add: tigr-nim

- packages.json
DNS Stamps package
https://github.com/rockcavera/nim-dnsstamps2
> Add package dnsstamps2

- packages.json
Add package implementing a standards-compliant parser and serializer for VCard3 files.
> Add package vcard.

- packages.json
The abstraction level is very shallow, still useful though.
> Add library package cozytaskpool

- packages.json
Few async tools for nim (then, catch, finally, and more)
https://github.com/archnim/sunk
> Add package sunk

- packages.json
command-line git repository manager
Source: https://github.com/nirokay/gitman
> added gitman to packages.json

- packages.json
A template processor and language.
> Add statictea.

- packages.json
nimcatapi is a library that lets you easily requests images from thecatapi.com and/or thedogapi.com!
> added nimcatapi to packages.json

- packages.json
Measures is a small library to provide measuring unit datatypes with integrated conversions and definitions. (More measurement units in the way)
> Add package measures

- packages.json
This PR adds a new hybrid Nim package.
Name: nimip
Description: Asynchronously lookup IP addresses with this tiny, hybrid Nim application.
> Add package nimip

- packages.json
nimegenerator is a random word/name generator.
> Add package nimegenerator and add nimcatapi html docs link

- packages.json
Brainfuck interpreter with some advanced features, such as syntax checking and highlighting errors.
> Add package brainimfuck

- packages.json
Google Trends RSS
https://git.ozzuu.com/thisago/gtrends
> Add package gtrends

- packages.json
Spotlightr basic extractor to get the video
https://git.ozzuu.com/thisago/spotlightr
> Add package spotlightr

- packages.json
Nim interface of Google Bard free API
https://github.com/thisago/bard
> Add package bard

- packages.json
Document IDs generation and validation
https://github.com/thisago/docid
> Add package docid

- packages.json
A pure Nim alternative to std/random, built with adding more RNG algorithms in mind.
https://github.com/xTrayambak/librng
> Add librng

- packages.json
Command line interface for Google Bard
https://github.com/thisago/clibard
> Add package clibard

- packages.json
nim implementation of bcs serialization format
https://github.com/C-NERD/nimBcs
> Add package bcs

- packages.json
Layout helpers and sugar for Karax
https://github.com/moigagoo/karkas
> Add package karkas

- packages.json
extensible performant tcp, udp, http and web socket proxy server
https://github.com/C-NERD/dan_magaji
> Add package dan_magaji

- packages.json
A library to quickly generate functions converting instances of type A to B
https://github.com/PhilippMDoerner/mapster
> Add package mapster

- packages.json
this package is self explanatory, it provides a cmp function that can be used with std/algorithm.sort to sort the given sequence of strings based on the content. The cmp function devides the strings into two and converts all the integer parts of them. Then it compares strings and integer parts separately.
> Added package "namenumbersort"

- packages.json
This library provides utilities for (standard) propositional logic.
> Add propositionalLogic

- packages.json
> Added libstrophe wrapper

- packages.json
Extract Podia sites courses data
https://github.com/thisago/getpodia
> Add package getpodia

- packages.json
Static html and css generator with many pre-made procs. For example `p("Text")` will generate onto which the `$` proc can be applied to generate the `<p>Text</p>` html string.
> Add package websitegenerator

- packages.json
A dirty and free way to use ChatGPT in Nim
https://github.com/thisago/dirtygpt
> Add package dirtygpt

- packages.json
Command line interface for ChatGPT
https://github.com/thisago/cligpt
> Add package cligpt

- packages.json
Shopify ecommerces data in a instant
https://github.com/thisago/shopifyextractor
> Add package shopifyextractor

- packages.json
Also changed description and removed some tags
https://github.com/thisago/iecook
> Renamed gookie to iecook

- packages.json
Instagram internal web api implementation
https://github.com/thisago/instagram
> Add package instagram

- packages.json
Realised it'd be much nicer to do this aha
> Rename package to be same as source

- packages.json
cross-compilation/release toolchain for nim powered by `zig`
> add package forge

- packages.json
A collection of extra utilities for Nim.
https://github.com/jjv360/nim-stdx
> Add package stdx

- packages.json
The easiest way to interact with a graphql api
https://github.com/arashi-software/zuhyo
> Add package inquire

- packages.json
I am planning to merge it with the main codebase, I might add a new and better package to the list someday.
> Remove package 'libpothole'

- packages.json
Multi backend HTTP fetching
https://github.com/thisago/unifetch
> Add package unifetch

- packages.json
webidl to Nim bindings generator
https://github.com/ASVIEST/webidl2nim
> Add package webidl2nim

- packages.json
This should be the last of my edits for a long while now
> Add docs to ModernNet and Crockfordb32 (my two other libraries)

- packages.json
A few CLI utilities
https://github.com/pcarrier/bz
> Add package bz

- packages.json
json parsing library based on bindings of simdjson
https://github.com/sainttttt/gemmaJSON
> Add package gemmaJSON

- packages.json
Parse a HTML document in Nim.
https://github.com/nim-lang/htmlparser
Edit:
This is not my work and I do not wish to claim that it is, I am doing this as a stand in for ringabout.
> Add package htmlparser

- packages.json
Allocate closures on stack
https://github.com/guibar64/stackclosures
> Add package stackclosures

- packages.json
A tool to capture and replay command line terminal sessions
https://github.com/crashappsec/cap10
> Add package cap10

- packages.json
https://github.com/theAkito/zoominvitr
> Add Zoominvitr

- packages.json
a very clean way of adding color to strings
> add package paint

- packages.json
> Fixed incorrect license being displayed

- packages.json
webpage information extractor
https://github.com/bung87/webpage_extractors
> Add package webpage_extractors

- packages.json
Awesome simple HTTP client for Nim 
https://github.com/mishankov/yahttp
> Add package yahttp

- packages.json
highly customizable terminal boxes for nim!
https://github.com/ptVoid/noxen
> Add package noxen

- packages.json
MIDI file parser in Nim, for Nim
https://github.com/Mycsina/NiMIDI
> Add package niMIDI

- packages.json
> Add nimpk and gura

- packages.json
An extended INI parser for Nim.
https://github.com/systemonia/iniplus
> Add package iniplus

- packages.json
Utilities for handling paths
https://github.com/hmbemba/pathutils
> Add package pathutils

- packages.json
Official Nim port of Sqids. Generate short YouTube-looking IDs from numbers.
https://github.com/sqids/sqids-nim
> Add package sqids

- packages.json
Special iterators that use move semantics
https://github.com/sls1005/moveiterators
> Add package moveiterators

- packages.json
> Added Note

- packages.json
calendar with local holidays via ip location
https://github.com/inv2004/ccal
> Add package ccal

- packages.json
Use threads as if they were servers/microservices to enable multi-threading with a simple mental model.
https://github.com/PhilippMDoerner/Appster
> Add package threadButler

- packages.json
Small package with my preferred API for byte ordering things: https://github.com/auxym/bight
> Add bight package

- packages.json
nim port of the icecream python library
https://github.com/hmbemba/icecream
> Add package icecream

- packages.json
https://github.com/ThomasTJdev/mummy_utils
> Utility package for mummy multithreaded server

- packages.json
Adding a package for HTML templating that I wrote
> Adding Templater package

- packages.json
POSIX compliant command line parser
https://github.com/amnr/getopty
> Add package getopty

- packages.json
High level SDL 2.0 shared library wrapper
https://github.com/amnr/nsdl2
> Add package nsdl2

- packages.json
High level SDL 1.2 shared library wrapper
https://github.com/amnr/nsdl1
> Add package nsdl1

- packages.json
High level SDL 3.0 shared library wrapper
https://github.com/amnr/nsdl3
> Add package nsdl3

- packages.json
Easy-to-use json serialization capabilities, with a drop-in replacement for std/json
https://github.com/codex-storage/nim-serde
> Add package serde

- packages.json
Hi! `nimplex` is concise scientific Nim library (with CLI and Python binding) providing samplings, uniform grids, and traversal graphs in compositional (simplex) spaces. Regarding this submission:
- The `nimble` branch is formatted to match Nimble directory structure and we suggest installing from it.
- Tests are present and can be quickly run with `tests/runAll.nim`.
> Add package `nimplex`

- README.md
> Clarify documentation on how to flag packages 

- packages.json
StatsD compatible daemon in pure Nim
https://github.com/Q-Master/statsdaemon.nim
> Add package statsdaemon

- packages.json
Pure nim rabbitmq to statsd metrics pusher
https://github.com/Q-Master/rmq-statsd.nim
> Add package rmq_statsd

- packages.json
A front-end web server specialized for real-time message exchange
https://github.com/zenywallet/caprese
> Add package caprese

- packages.json
GUI&CUI application and library for [Puyo Puyo](https://puyo.sega.jp/portal/) and [Nazo Puyo](https://vc.sega.jp/3ds/nazopuyo/).
https://github.com/izumiya-keisuke/pon2
> Add package pon2

- packages.json
Easy safe signal handling
https://gitlab.com/tdely/selfpipe
> Add package selfpipe

- packages.json
An Amateur Data Interchange Format (ADIF) formatter and parser.
https://github.com/clzls/nimAdif
> Add package nimAdif

- packages.json
Hi! `nimCSO` (nim Composition Space Optimization) is a high-performance tool that leverages Nim's compile-time metaprogramming to implement several methods for selecting components (data dimensions) in compositional datasets, as to optimize the data availability and density for applications such as machine learning.
Regarding this submission:
- API Documentation is available at [nimcso.phaseslab.org](https://nimcso.phaseslab.org)
- Tests are automated across 3 platforms with GitHub CI, and can be quickly run locally with `tests/runAll.nim` script.
- This code was developed for [ULTERA Project (ultera.org)](https://ultera.org) carried under the 
[US DOE ARPA-E ULTIMATE](https://arpa-e.energy.gov/?q=arpa-e-programs/ultimate) program.
> Add package `nimCSO`

- packages.json
add nginwho an nginx log parser:
https://github.com/pouriyajamshidi/nginwho
> add nginwho an nginx log parser

- packages.json
Extract syscall stats from strace output files
https://github.com/tdely/umriss
> Add package umriss

- packages.json
> Update packages.json for package 'vqsort'

- packages.json
terminal based audio station player in nim
https://git.disroot.org/bloomingchad/pnimrp
https://github.com/bloomingchad/pnimrp
> Add package pnimrp

- packages.json
> Add nimjl1534

- packages.json
Precise fraction math for nim.
> Added package pmath

- packages.json
🍬 General syntactic sugar
https://github.com/FyraLabs/sweet
> Add package sweet

- packages.json
Low-level Nim wrapper for Chrome DevTools Protocol (CDP) v1.3 stable. Bend Chrome to your will with complete control over your browser. Scrape dynamic webpages, create browser automations, and beyond.
https://github.com/Niminem/ChromeDevToolsProtocol
> Add package cdp

- packages.json
Classes and dependency injection for Nim.
https://github.com/YaDev/NimCLS
> Added package NimCLS

- packages.json
(updated?) Low-level Tcl & Tk bindings for Nim
https://github.com/neroist/nimtcl
> Add nimtcl

- packages.json
simpleMail: https://github.com/up7down8/simpleMail
asyncssh2: https://github.com/up7down8/asyncssh2
> add simpleMail and asyncssh2

- packages.json
Reactive programming, in nim
https://github.com/minamorl/rex
> Add package rex

- packages.json
Dimensional Analysis in Nim
https://github.com/lorenzoliuzzo/dim
> Add package dim

- packages.json
Detect if you are running as root, restart self with sudo if needed or setup uid zero when running with the SUID flag set.
https://github.com/FyraLabs/sudo.nim
> Add package sudo

- packages.json
A package for ingesting Texas Railroad Commission data, inteded as a first release.
> adding well_parser

- packages.json
Following packages to be added:
- shellcmd
- asyncproc
- aloganimisc
- asyncsync
- asyncio
- asyncsync
- csvdict
> Adding alogani nimble packages

- packages.json
Easter date calculation engine.
https://github.com/GeK2K/easter
> Add package easter

- packages.json
`UI` components for [HappyX web framework](https://github.com/HapticX/happyx)
> Add `happyx-ui` library

- packages.json
Some useful tools when working with dates.
https://github.com/GeK2K/nudates
> Add package nudates

- packages.json
git profile manager
https://github.com/tdely/dira
> Add package dira

- packages.json
nimble publish crashed with:
```
Prompt: Whitespace separated list of tags? (For example: web library wrapper)
leveldb library wrapper static static-linked
Answer:     Pushing to remote of fork.
Info Creating PR
httpclient.nim(322)      httpError
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```
So I'm pushing this button myself! :D
> Added package leveldbstatic

- packages.json
Library isn't too stable yet but 🤷🏾‍♀️
> Add nimtk package

- packages.json
What could I expect, editing json manually...
Sorry.
> Fix ` cozylogwriter` url

- packages.json
https://git.sr.ht/~ehmry/nim_lk
Already used in Nixpkgs: https://nixos.org/manual/nixpkgs/unstable/#nim-lockfiles
> Add package nim_lk

- packages.json
Business Days (or Working Days) calculator.
https://github.com/GeK2K/businessdays
> Add package businessdays

- packages.json
Easily create .gitignore files from your terminal
https://github.com/chrischtel/gitty
> Add package gitty

- packages.json
Simple structured console messages for Nim applications.
https://github.com/logavanc/shobiz
> Add package shobiz

- packages.json
Common utils for Nimscript
https://github.com/FyraLabs/nimsutils
> Add package nimsutils

- packages.json
* Chame: HTML5 parser <https://git.sr.ht/~bptato/chame>
* Chagashi: character coding library <https://git.sr.ht/~bptato/chagashi>
* Monoucha: high-level QuickJS wrapper <https://git.sr.ht/~bptato/monoucha>
> Add Chame, Chagashi, Monoucha

- packages.json
> Update url of pylib to an active fork

- packages.json
Initialize a Nim package non-interactively (does not require nimble)
https://github.com/cypherwytch/ninit
> Add package ninit

- packages.json
Cloths provides the way to process and structure string easily.
https://github.com/panno8M/cloths
> Add package cloths

- packages.json
> Update url of strenc

- packages.json
List out block-devices, including disks, partitions and their mountpoints
https://github.com/FyraLabs/lsblk.nim
> Add package lsblk

- packages.json
https://github.com/HapticX/happyx/actions/runs/9843065758/job/27173436427
> [FIX]: Deleted user

- packages.json
This package is a collection of API wrappers to fetch holidays and do some code wizardry on them.
> Add package HolidAPI

- packages.json
xxhash wrapper library for Nim
https://github.com/sainttttt/hannah
> Add package hannah

- packages.json
Added Batmon - a basic battery status change notifier.
> added batmon

- packages.json
Not a finished library but it works well enough to announce.
> Add wayland_native

- packages.json
https://github.com/mentalonigiri/niqlite
> add niqlite

- packages.json
A simple clap-like command line argument parser written in Nim
https://github.com/AinTEAsports/nclap
> Add package nclap

- packages.json
This package provides high level and memory safe* bindings over `simdutf`
> Add package simdutf

- packages.json
SurrealDB driver for Nim
https://github.com/Xkonti/surrealdb.nim
> Add package surrealdb

- packages.json
- add llama_leap, my client library for [Ollama](https://github.com/ollama/ollama)
- also add openai_leap, my client library for OpenAI (ChatGPT)
> Client libraries for Ollama and OpenAI

- packages.json
buju (布局) is a simple layout engine, based on layout.h
> Add package `buju`

- packages.json
2048 game clone runs in your terminal, written in Nim
https://github.com/enkaito/nim_2048
> Add package nim_2048

- packages.json
Add nimble pakage for katalis https://github.com/zendbit/katalis
> add nimble packate for katalis

- packages.json
Clear range maker
https://github.com/PegasusPlusUS/rangex-nim
> Add package rangex

- packages.json
[twim](https://github.com/aspiring-aster/twim) is a modern X/Twitter API library for Nim.
> Add package twim

- packages.json
project repository is [https://gitlab.com/Maxb0tbeep/bestfetch](https://gitlab.com/Maxb0tbeep/bestfetch)
> add package bestfetch

- packages.json
https://github.com/ThomasTJdev/nim_yubikey_otp
> Update packages.json - add yubikey_otp

- packages.json
Add the package "serverly" to packages.json
> Add serverly

- packages.json
* added readfx package
* fixed json
> add readfx

- packages.json
A slot and signals implementation for the Nim programming language
https://github.com/elcritch/sigils
> Add package sigils

- packages.json
argv and argc for command line arguments
https://github.com/threatfender/args
> Add package args

- packages.json
SIMD-accelerated multithreaded fuzzy search thats fast as f*ck
https://github.com/arashi-software/floof
> Add package floof

- packages.json
Added package "nivot", a simple pivot library for nim
> Added package "nivot", a simple pivot library for nim

- packages.json
A simple, powerful terminal coloring and styling library akin to NPM `colors`
https://github.com/thing-king/colors
> Add package colors

- packages.json
An extension of `jsony` supporting better hooks, and type creation from schemas
https://github.com/thing-king/jsony_plus
> Add package jsony_plus

- packages.json
Modern networking interfaces for Nim.
https://github.com/WKHAllen/nimdtp
> Add package nimdtp

- packages.json
Converts JSON schema definitions to nim types
https://github.com/Nycto/NimJsonSchemaImporter
> Add package json_schema_import

- packages.json
Nim client for the DataForSEO API (v3). Zero dependencies, supports both sync and async requests.
https://github.com/Niminem/DataForSEO
> Add package dataforseo

- packages.json
DbC library for Nim providing precondition and postcondition assertions
https://github.com/alexekdahl/assert
> Add package assert

- packages.json
CSS parser and validator
https://github.com/thing-king/css
> Add package css

- packages.json
> Update packages.json - add katabase to package list

- packages.json
dumb MD4 digest calculation 
https://github.com/Infinoid/md4.nim
> Add package md4

- packages.json
ED2Ksum hash calculation
https://github.com/Infinoid/ed2ksum.nim
> Add package ed2ksum

- packages.json
Sort imports in Nim source files
https://github.com/cycneuramus/nimpsort
> Add package nimpsort

- packages.json
Typed HTML5 element data and builder for structured HTML
https://github.com/thing-king/html
> Add package html

- packages.json
Lifts compile-time object to AST
https://github.com/thing-king/lifter
> Add package lifter

- packages.json
> Add the nim-kuzu wrapper.

- packages.json
cc original author @markspanbroek and @dryajov from Codex
> Use new repo name of questionable

- packages.json
Rust-like match syntax macros for Nim
https://github.com/voidpunk/NiMatch
> Add package nimatch

- packages.json
pharao is a mummy server that compiles and run nim files so you can use them with the same workflow as PHP
> add pharao

- packages.json
Links Nim packages via `srcDir` correctly
https://github.com/thing-king/nimlink
> Add package nimlink

- packages.json
Programmatically manage jobs in a Nomad cluster
https://github.com/cycneuramus/nmgr
> Add package nmgr

- packages.json
Loads IP blocklists into nftables from plain text or JSON feeds
https://github.com/cycneuramus/deceptimeed
> Add package deceptimeed

- packages.json
Adds [nimsight](https://github.com/ire4ever1190/nimsight/) package
> Add package `nimsight`

- packages.json
Add https://github.com/nitely/nim-hyps
> Add hyps package

- packages.json
Amicus contains the database code for Onbox
> add amicus

- packages.json
ThorVG Nim Wrapper
https://github.com/elcritch/thorvg-nim
> Add package thorvg

- packages.json
Scope tracking for untyped macros
https://github.com/thing-king/scope
> Add package scope

- packages.json
> added sdl3_nim

- packages.json
> Add package ukpolice

- packages.json
See https://github.com/julienaubert/nim-sndfile/issues/8#issuecomment-2407846621
@julienaubert
> feat: change URL for nim-sndfile due to change of maintainer

- packages.json
An optimized and highly efficient Nullable / Optional type for Nim. Designed for performance-critical applications, it provides clear, functional-style handling of optional values, especially for value types, without reference overhead.
https://github.com/theDataFlowClub/nullable
> Add package nullable

- packages.json
Discrete Wavelet Transform (DWT - here 'dewitt') for Audio Analysis
https://github.com/Luteva-ssh/dewitt
> Add package dewitt

- packages.json
> Add package nationalize

- packages.json
Fast as Fuck interpolated LUT generator and applier
https://github.com/arashi-software/clutter
> Add package clutter

- packages.json
A CLI tool and library for interacting with various LLMs
> add seance

- packages.json
> Add package NiFe

- README.md
ref https://github.com/nim-lang/packages/issues/2995
> recommendation of https://nimpkgs.dayl.in

- packages.json
Lightweight, zero-dependency Nim library with expressive helper APIs for numbers, strings, and collections
https://github.com/alexzzzs/NimTools
> Add package nimtools

- packages.json
xcb.nim | Nimmified bindings for XCB
https://github.com/heysokam/xcb.nim
> Add package xcb_nim

- packages.json
https://github.com/tsoj/nimchess
> Adding nimchess to packages.json

- packages.json
The project is "unsupported", and the web site that serves and documents it is down.
Created in response to https://forum.nim-lang.org/t/13305 
cc. @al6x OK?
> Remove https://github.com/al6x/pl0t

- packages.json
Make your terminal interfaces prettier!
https://github.com/CodeLibraty/prettyterm
> Add package prettyterm

- packages.json
Just a simple vibe coded package for parsing mmCIF files with python bindings
> add mmcif package

- packages.json
I am releasing a new library called Fidget2, based on my older library called Fidget. I released Fidget about four or five years ago. After that I worked mostly on low level libraries like Pixie, Windy, Boxy, VMath, Bumpy, and others to make the full UI stack work. Now I have been working on Fidget2, and I think it is finally ready to release.
> Add fidget2.

- packages.json
A stupid simple Markdown library
https://github.com/openpeeps/marvdown
> Add package marvdown

- packages.json
Added nimgnuplot, my interface to gnuplot featuring Damancer dataframe support.
> Added package nimgnuplot.

- packages.json
Cipherlib is a nim library that features classical ciphers like Caesar and vigenere for encoding and decoding of text with these ciphers.
> Added cipherlib: a nim package for cipher encoding and decoding
