- packages.json
I added a small library that had been requested on this thread: http://forum.nim-lang.org/t/323.
I'm aware of the similar `optional_t` package, but...
1. My package uses casting and `{.noInit.}` to avoid overhead. This is important for implementing efficient generic source/sink operations, like [D's range library](http://dlang.org/phobos/std_range.html), and sped up many of my benchmarks by over a factor of 5 (making them equivalent to raw loops, performance-wise).
2. My package is designed with naming/API conventions that are consistent with a much larger project I'm working on, as well as with the standard library (when to use `typedesc` vs explicit generic parameters, when to use adjectives vs. verbs vs. nouns, etc.) It may be a minor point, but my project is aimed at new developers, …
> Added `optionals`

- packages.json
I noticed the URL being git:// on http://nim-lang.org/lib.html
> Add web url for commandeer

- packages.json
Seems like it was copied from the previous entry and still points to the old webpage. Didn't affect the download url.
> Fixed up a copy/paste issue

- packages.json
Added a base62 package for nimble.  It's MIT-licensed and should be set up as a nimble package at https://github.com/singularperturbation/base62-encode.
> Added base62 package

- packages.json
emerald has now a documentation page at GitHub Pages.
> emerald: updated web URL

- packages.json
The name of the package should match the name of the compiled binary file really...
> fix: LiteStore -> litestore

- packages.json
Fixes https://github.com/jovial/nim-libclang/issues/2
@jovial, Please acknowledge.
> Renamed nim-libclang to libclang.

- packages.json
Fixes package location of bitarray package following org rename in Github
> Update bitarray package location

- packages.json
nimbench is supported on platforms windows, macos and posix.
Request to add nimbench 0.1.1 to nimble package listing.
> Add nimbench package

- packages.json
Adding the `pledge` package, which adds an easy accessor to OpenBSD's [`pledge(2)`](http://man.openbsd.org/OpenBSD-current/man2/pledge.2). On unsupported operating systems (e.g.: not OpenBSD), it provides a replacement function that always succeeds.
> Add package pledge

- packages.json
As a "learning nim" project I've created a port of the cucumber testing framework into nim. As this is my first project, I'm sure it could use a good deal of cleanup. It does run its own tests, at least.
> Adding "cucumber_nim"

- package_scanner.nim
- packages.json
git protocol is absolutely insecure, so we should not be using it by default. If a user really wants to use `git://` they can set this in their git config:
[url "git://"]
insteadOf = https://
> Use secure https instead of insecure git protocol

- packages.json
This is a (temporary?) change to nim-only-uuid link. The author of the original repo (@wheineman) does not respond to pull requests. Original lib (https://github.com/wheineman/nim-only-uuid) does not compile with latest nim. @wheineman, please change the link back whenever you're available :)
> Changed nim-only-uuid link to yglukhov

- packages.json
Nim's `json` module allows it, but the native parser used for JS does not, leading to this error:
http://forum.nim-lang.org/t/2504
> JSON does not have an escape sequence for '

- packages.json
Exdend with forestDB. Base is under https://github.com/couchbase/forestdb. Nim bind is under: https://github.com/nimscale/forestdb.
> Added nim bind for forestDB.

- packages.json
Since the existing termbox wrapper is out of date and quite low-level, I've written a new one which uses c2nim to generate a low-level wrapper and created an OOP-style wrapper around that. This library is heavily inspired by [Rustbox](https://github.com/gchp/rustbox).
> Add nimbox, a simple termbox wrapper

- packages.json
I mixed up the licenses when originally adding nimbox. I think I got confused with another project, which _is_ licensed under the GPLv3.
> Fix license for nimbox

- packages.json
This isn't really an issue, since GitHub redirects, but it's confusing and a bit disconcerting to see nimble install from Araq/Nim.git instead of nim-lang/Nim.git
> Update URL for `compiler` to point to nim-lang

- packages.json
This is a takeover of [nim-jwt](https://github.com/ekarlso/nim-jwt) because the original library is not compilable and the author doesn't respond for pull requests. My fork also adds support for new signature algorithms: HS384, HS512, RS256, RS384 and RS512. @ekarlso, please feel free to revert this PR whenever you're ready to maintain it again.
> nim-jwt takeover

- packages.json
This is just a small wrapper for libevdev, the Linux input processing library. I used it for handling the touchscreen on a Raspberry Pi.
It's possible it's not very "Nim-like", in that I just ran c2nim and then fixed up the errors. That means that the structures returned are all raw pointers, which should be fine if cleaned up using the API, but also means they can't be GC'd.
> Add libevdev, low-level Linux input processing

- packages.json
Fixes name clashing with stdlib_registry
> Rename package registry to winregistry

- packages.json
Colorize is a simple and lightweight terminal coloring utility to quickly make your terminal outputs beautiful.
> Adding colorize

- README.md
Would be helpful for users if there was a link to the standard library documentation. Especially because Google ranks this repo higher than the docs page searching for _"nimble packages"_, and it is the package overview that is important for users.
> added link to standard library

- packages.json
`nim-gmp` is an unmaintained package that's fallen out of compatibility with nimble. I've forked it and made a trivial change to restore compatibility.
> Highjack nim-gmp

- packages.json
`libserialport` was a misleading name as it implied the library was a wrapper.
> Rename `libserialport` to `serial`.

- packages.json
Adding [zero-functional lib](https://github.com/alehander42/zero-functional) (is the name with `-` ok? I am not sure if there is a convention here). I can also rename it e.g. to `chain` or `chain-functional` if the name looks confusing
> Add zero_functional entry

- packages.json
[webview](https://github.com/oskca/webview), a Nim bindings for https://github.com/zserge/webview, a cross platform single header webview library
> add webview, a cross platform single header webview library

- packages.json
OK, fixed the problem I had last time. Everything uses GNU vector intrinsics internally now, so there aren't any major performance deficiencies compared to scalar-- it should be much faster than scalar code, as SIMD should be.
Again, if I did anything incorrectly, such as package structure, let me know.
> Add package sol

- packages.json
I'm adding these two packages in the same PR because nimpb kind of needs nimpb_protoc to be useful.
> Add nimpb and nimpb_protoc

- packages.json
The library `turn_based_game` is a rules engine that assists in writing games that are...well...turn-based. (The meaning of that is well documented in the wiki.) One of my next projects is porting my Negamax AI algorithms to nim, and they will require this framework to predictably operate.
> Added turn_based_game to list of packages.

- packages.json
Since the documentation can be generated automatically during testing jobs on gitlab,
the documentation on github won't be updated anymore.
The github repository will be left as a mirror though.
> The NESM package has been moved to gitlab

- packages.json
Renamed websitecreator to nimwc due to changing structure for complying with Nimble.
https://github.com/ThomasTJdev/nim_websitecreator / https://nimwc.org
> Renamed websitecreator to nimwc

- packages.json
Adds the nimrun package (https://github.com/lee-b/nimrun), which is a shebang wrapper that allows execution of standalone nim files on unix.  This differs from nimcr in that .nim extensions aren't required, that the script directory isn't polluted, and that nimble is used for compilation.
> Add nimrun package

- packages.json
We renamed the `.nimble` file into `torch.nimble`
Would be wise to keep both flavors the old `nimtorch` (not so correct API wise but works) and the new flavor `torch`
> Add torch package variation to nimtorch

- packages.json
- Cleanout, No new package.
- Remove package `vardene` because no longer exists https://github.com/Xe/vardene
- Fix Redux package having empty strings as tags.
- Fix empty strings as tags on other packages.
- Remove `"The "` from the License, eg. like `The GPL` instead of `GPL`.
- Remove `" License"` from the License, eg. like `GPL License` instead of `GPL`.
:smile:
> Cleanout, No new package

- packages.json
I changed my username months ago and have been relying on github redirects but I don't want to hold my breath on them. Also changed the tags to properly reflect the library.
> Changed links to proper repos and tags

- README.md
The referenced section was removed from Nim's documentation.
> remove readme link to Nim "library overview"

- packages.json
Netpipe is a reliable UDP connection for Nim.
> Add netpipe library.

- packages.json
Update the license for https://nimwc.org from GPLv3 to PPL.
> Update license for NimWC

- packages.json
In the packages.json it was listed as MIT but on their git repo the license is LGPLv3.
> Updated Omnilog's license

- packages.json
The original repo https://github.com/FedeOmoto/bignum hasn't been
maintained in many years.
I am not an expert in bignum but I am maintaining a fork of it that
runs with the latest stable Nim version (v0.20.0 as of today).
> Updating the bignum package source to a fork that works on Nim 0.20

- packages.json
I forked [this repository](https://github.com/flaviut/easy-bcrypt) and fixed https://github.com/flaviut/easy-bcrypt/issues/2. I changed the package information within the packages list to my fork. The module works exactly the same as before, except you can actually install it via nimble now, as well.
> Updated and fixed "easy_bcrypt"

- packages.json
This patch changes the twitter package maintainer. @kubo39 is the original developer, but has decided to archive the project, so no further pull request can be made.
The forked version `0.2.1` fixes the build issues due to changes in latest nim.
> Change twitter package maintainer

- packages.json
Nim port of Cirru syntax parser, related to https://www.npmjs.com/package/cirru-parser and https://github.com/Cirru/parser.nim .
Since the process of `nimble publish` stalled, this PR is made by hand.
The code uses `cirruParser` for importing, I saw other packages prefer using `-` so I changed it back to `cirru-parser`.
> Add cirru-parser

- packages.json
While adding a LICENSE file to my repo (#1183), I decided to switch to something more permissive.
> Change sunvox bindings license to 0BSD

- packages.json
It's for benchmarking runtime or compilation.  Here's a handy link:
https://github.com/disruptek/golden
> Added package golden

- packages.json
Hi, this package would be breaking the "Tiny libraries should be avoided where possible" requirement. So I understand if it is not incorporated into the list. But at least I should try ^w^!
> Add package owo

- packages.json
https://gitlab.com/define-private-public/stb_image-Nim/issues/9
User was having trouble installing the package via nimble.  Suggested I add `.git` at the end of this package's `url` to fix it.
> Fix stb_image `url`

- packages.json
This is a simple library to get information on files and folders in OneDrive. The library requires a public shared url to your OneDrive folder, which allows public access to files.
When querying your OneDrive data, you get the data on the folder, and information on possible sub-folders and files. Normal querying only travel 1 level down, but the lib includes a deep-diver, which currently goes 3 levels down.
The library output objects for files (OnedriveFile) and for folders (OnedriveFolder).
The library uses the old URL https://api.onedrive.com/v1.0/shares/u! which is not requiring any external libraries or accounts at OneDrive. This library does not support Microsoft Graph at the moment.
> Add onedrive library

- packages.json
This adds to nimble a high-level [OAI-PMH](https://www.openarchives.org/pmh/) library for nim.
> Add oaitools.

- packages.json
nim.uri3 is a Nim module that provides improved way for working with URIs. It is based on the uri module in the Nim standard library and fork from nim-uri2 with some bug fix and performance
> Add nimble package uri3

- packages.json
You provide the URL to the stock on www.nordnet.dk, and this little Nim program provide you with the latest data on the stock.
You can use this library in 3 ways:
1. Normal library, either by cloning the repo or installing with Nimble
2. CLI tool which outputs the data to the console
3. Home Assistant "plugin" to serve data to your dashboard
> Add nordnet

- packages.json
NimCoon is a thin wrapper over youtube-dl, mpv and peerflix that allows you to stream or download music and video from sites like YouTube, PeerTube and magnet links.
> Add package nimcoon

- packages.json
I accidentally linked to the original Lisp implementation of mine this was ported from. Sorry about that.
> origin: Fix web link typo

- packages.json
adding a new package that wraps libclang c interface. i realize there is an existing library package but it is many years out of date and combines all the headers into one file, rather than mirroring the headers.
> adding updated libclang-c wrapper package

- packages.json
Since I have renamed my GitHub username to `fredrikhr` the package listing has to be updated to reflect that.
GitHub maintains a redirect from the old to the new repository url, so users with outdated package listings will still be able to download the package using the old url.
> Change couven92 to fredrikhr

- .gitattributes
Sadly, github doesn't support this (yet), so this will not affect merges via the Github WebUI.
> Make packages.json use the union merge strategy

- packages.json
Flatty - serializer and tools for flat binary files.
Aim of flatty is to be the best serializer/deserializer for nim.
Also includes hexprint to print out binary data.
Also includes binny a simpler replacement for StringStream (no IO effects, operates on a string)
Also includes hashy a hash for any objects based on the serializer.
> Add flatty library

- packages.json
Seems to be no longer in Nim (Nim repo was likely deleted and recreated as a Go library). We really should consider forking and syncing Nimble packages :)
See https://github.com/recoilme/pudge
> Remove pudge (it's a Go library now)

- packages.json
Single-producer, single-consumer, lock-free queue (aka ring buffer) implementations for Nim.
Further package info @ https://github.com/elijahr/lockfreequeues
> Add package lockfreequeues

- packages.json
I created a nimnews package (a simple newsgroup NNTP server) and I added it to the nimble directory. it's very early and immature, but I supposed that making it discoverable was a good thing. This is my first contribution to nimbles so please excuse any errors I might have made.
> Add nimnews to nimble directory

- packages.json
The current owner did not respond to my PR to add support for uploading media to twitter for 30 days and I have added a bunch of procs for doing this, his bio also says 'not hosting on github'
I don't really want to step on anyone's toes here but it seems like the default 'twitter' package should at least support requests to the media endpoint.
> Change twitter.nim owner

- packages.json
Add `jupyternim` to nimble.
I finally feel like the experience is "good enough" when using jupyternim, despite limitations with mimicking a repl and missing code completion and inspection.
> Add jupyternim to nimble

- packages.json
std::bitset implementation in pure nim, with identical signatures. It also includes the same kind of raw memory layout behavior enabling byte-level casting, just like std::bitset. I personally needed this while porting something from c++ to nim, so thought I would make it public. The memory/casting requirement meant I could not use the other 4+ packages others have already written.
```nim
import bitset
var bs:Bitset[210] # 210 bits, or 27 bytes allocated (not all of 27th byte used)
bs[0] = 0 # not necessary
bs[1] = 1
bs[2] = 1
bs[3] = 1
echo bs # 0000...<redacted>...00001110
assert bs.len() == 210
assert sizeof bs == 27
assert bs.bytes[0] == 14
assert bs.count() == 3
assert bs.unsafeAddr == bs.bytes[0].unsafeAddr
```
> Add package bitset

- packages.json
This adds `latexdsl` and `rnim`. `rnim` is really rough around the edges, but if this brings some more eyes to the project that'd be helpful.
Also I take over maintenance of `nblosc`, because @Skrylar has since archived their repository.
> add latexdsl, rnim, take over nblosc maintenance

- packages.json
Looks like the "web" attribute was accidentally set to invalid value when a block of nimtreesitter-related packages was added.
> Fix "web" URL for nimterop

- packages.json
Project is migrating to https://github.com/calcit-lang/ternary-tree .
Added in https://github.com/nim-lang/packages/pull/1683 .
> Update url for ternary_tree

- packages.json
Owner does not respond to Github issues and pull request.
* Issue for updating the version tag to include latest commit the 2020-04-17.
* PR for fixing compiling issues the 2020-04-17 with 5 reminder messages.
* Owner hasn't pushed to Github since 2020-04-21.
If original owner one day wants the repo back, then all fine by me.
> Change ownership of nimlibxlsxwriter

- packages.json
Differences to the existing oshostname package:
* All popular operating systems are supported.
* Supports setting hostname.
Tested manually on Fedora 33 and Windows Server 2019 with Nim 1.4.2.
> Add package hostname

- packages.json
The [original version](https://github.com/rnowley/nim-ncurses/) has an out of date .nimble file which does not work with the current version of nimble.
See [this issue](https://github.com/rnowley/nim-ncurses/issues/21) in the original repo. Someone made a [PR](https://github.com/rnowley/nim-ncurses/pull/25) with a fix, but the maintainer seems inactive.
I forked the repo, fixed the .nimble file and corrected a compiler error within ncurses.nim.
> Move to working fork of ncurses wrapper

- packages.json
The `hats` module exposes two types of [hashed array tree](https://en.wikipedia.org/wiki/Hashed_array_tree). The github repo is available [here](https://github.com/davidgarland/nim-hats).
* `add` and `pop` are *true* (not amortized!) O(1) by spreading the work of block pointer copies across operations.
* Indexing is O(1) with two layers of indirection rather than the usual one layer, so slightly slower than `seq[T]` for some use cases, but still pretty fast.
* Iteration using `items` only dereferences the blocks once, so it turns out to be as fast as iterating over a `seq[T]` most of the time.
* Space wastage for both is O(n)
Where the two differ is that `HatD[T]` uses increasing power-of-two sub-block sizes, therefore wasting more element space and less pointer space at large sizes, …
> Add package hats

- packages.json
A wrapper around [liblo](https://github.com/radarsat1/liblo) for the OSC protocol.
> Added package nimosc

- packages.json
Moved to github because nimble.directory doesn't show package description when a repository is hosted outside github. No ETA to fix this.
([https://github.com/FedericoCeratto/nim-package-directory/issues/35](https://github.com/FedericoCeratto/nim-package-directory/issues/35))
> edited package sources, moved to github

- packages.json
Karax has been moved to https://github.com/karaxnim/karax/, so it should be updated accordingly
> Update Karax location

- packages.json
AWS Security Token Service API in Nim
This nim package is for generating AWS Security Token Service and temporary ASIAxxx credentials.
> Add "awsSTS"

- packages.json
Moved the `polynumeric` package to the SciNim organization.
> update URL of `polynumeric`, now under SciNim umbrella

- packages.json
I added support for ISO 15924 (language scripts) and ISO 4217 (currencies) to `isocodes`.
> Update isocodes tags and description.

- packages.json
[Nordaudio](https://github.com/Psirus/nordaudio) is a small wrapper around PortAudio for cross-platform audio IO.
> Add nordaudio package

- packages.json
Metatag is a metadata reading & writing library, supporting id3v2.3.0 and flac, written from scratch in nim.
> Add package metatag

- packages.json
that library has an invalid repo link
> Abandon `ogg`

- packages.json
adds `watcher`.
Queue watcher helps monitor TCP connections and diagnose buffer and connectivity issues on Linux machines related to input and output queues
> add qwatcher

- packages.json
The repo is already archived, mainly because there are quite a lot of issues with term-rewriting macros for this package.
> Abandon strenc

- packages.json
Adds dimage, a small library that I extracted from a larger project. It allows you to pull mime type and size information from images. It is written in pure Nim and has cligen as its only dependency except for the Nim stdlib.
> Adds dimage

- packages.json
The eris_utils package was merged into the eris package.
https://codeberg.org/eris/nim-eris/commit/290da6ed1abcb538fe62b100507b3cf4efbf6bdf
> Remove eris_utils

- packages.json
Original repository uri for my package was pointing to the ssh endpoint.
> Authenticode package repo url fix

- package_scanner.nim
As I said in #2300, some packages have empty tags, this PR modifies `packages_scanner.nim` so that it warns when packages have empty tags.
Since I'm already making this PR I wanted to know if I should add the following changes to this PR or make a new: add a `config.nims` file with `--define:ssl` and check for valid `JsonNode` kinds (check that `tags` is a `JArray` of `JString`s, `url` is a `JString` and so on).
:heart:
> Check for empty tags

- packages.json
`toposort` provides a generic, efficient topological sorting implementation based on Kahn's algorithm. It also offers hash collision detection.
`resolver` provides a bunch of utilities for working with versions and dependencies. Right now, it includes:
- fully compliant semver parsing
- fully compliant semver comparison, including inspection of pre-release tags
- a well-defined versioning language with 6 operators: `>=` `<=` `^=` `~=` `and` `or`
`resolver` may get more features in the future - eventually, it will provide tools that aid in locating dependencies, arranging them in topological order, and creating lockfiles. The existing APIs won't change.
> Add toposort and resolver to packages.json

- config.nims
- package_scanner.nim
- packages.json
- Created `config.nims` with `--define:ssl` for easier compilation.
- Added a `-d:dontFetchRepos` (devel only) flag that makes `package_scanner.nim` don't call `canFetchNimbleRepository`. This is useful for testing changes without having to fetch over 2000 repositories (especially with slow internet).
> -d:dontFetchRepos and config.nims

- packages.json
I picked up the old nimp5 repo from @Foldover and started fixing and adding stuff. Also it was renamed to p5nim (from nimp5)
He is ok to remove his version and add mine: https://github.com/Foldover/nim-p5/pull/2#issuecomment-1336357474
https://github.com/pietroppeter/p5nim
> rename nimp5 to p5nim + alias + change repo

- packages.json
Low level db_sqlite and db_postgres forks with a proper typing
This is a fork of the already existing ndb, which appears to no longer be actively maintained. I forked this for future nim2.0 compatibility and for usage in norm.
https://github.com/PhilippMDoerner/lowdb
> Add package lowdb

- packages.json
`kroutes` is a client-side router for Karax. While it is mostly focused on client-side rendering applications, it also supports server-side rendering.
The repo includes a demo app that exercises `kroutes` core functionality.
> Added package kroutes

- LICENSE-GPLv3.txt
- LICENSE.txt
- README.md
Package scanner is GPLv3 licenses, everything else is CC-BY. This is documented in the readme.
Closes #2522
> Add licenses for package list and package scanner

- .github/workflows/testpr.yml
- .github/workflows/testpush.yml
- getmergebase.sh
- package_scanner.nim
- validate_json.js
Changes to the original package scanner:
1. Can compare two package lists and only check the modified packages.
2. Checking the availability of URLs is now a runtime option.
3. Checks not just the web URL for availability but also docs and download URLs.
4. All URLs are ensured to be https.
5. License checking has been removed as it produced too many false positives and lead to merges being delayed by months because of a failed CI status.
6. Package names are checked against a character whitelist. This can be used in the future to make sure names are valid identifiers in Nim.
7. Duplicate package names are reported for all occurences of the name instead of only starting at the second occurence. Their URLs are printed to help with resolving the situation.
8. The special tag "deleted" marks …
> Implement new package scanner

- packages.json
User @ijneb renamed to @refaqtor
Importantly for https://github.com/nim-lang/packages/issues/1807:
In this case the old username is occupied so automatic tools would incorrectly show the packages as deleted, when they've been moved!
> Update nimetry, algebra links

- packages.json
This PR adds a new package named **mcsrvstat.nim**, a hybrid and asynchronous Nim wrapper for the Minecraft Server Status API.
> Add package: mcsrvstat.nim

- packages.json
These are new bindings compatible with the latest version of OpenCV. (4.7.x as of today.) MVB stands for "Minimum Viable Bindings" and/or "Machine Vision Bindings" (🖥️👁️📒). The library is minimal at the moment, but it can read and display from the camera, and read/write and encode files. These are the absolute minimum features required for a viable OpenCV binding. The plan is to keep improving the bindings until MVB is an acronym for "Maximum Viable Bindings".
> Add package mvb

- packages.json
A simple colored logger from std/logging.
Adding some colors to make it easier to notice the important logs.
https://github.com/4zv4l/colored_logger
> add colored_logger to packages.json

- packages.json
Adds NimPath, which is a small library that allows you to parse html/xml using libxml2's XPath interface.
> Add nimpath

- packages.json
Software artifact metadata to make it easy to tie deployments to source code and collect metadata.
https://github.com/crashappsec/chalk
> Add package chalk

- packages.json
Add the [hyprland_ipc](https://github.com/xTrayambak/hyprland_ipc) package which allows you to customize the [Hyprland](https://github.com/hyprwm/hyprland) Wayland compositor via its IPC.
> (add) add hyprland_ipc

- packages.json
This tool lets you replace specific substrings in .docx files.
Useful for meeting and meeting-summary documents, as it can insert arbitrary data, such as participant names, and dates.
> Add docchanger

- packages.json
The reason is that in view of the EU’s Cyber Resilience Act and an abundance of caution, I have withdrawn all my free software (see https://en.wikipedia.org/wiki/Cyber_Resilience_Act#Criticism ).
> Update packages.json: removed my diff package

- packages.json
A fork of jester updated to work with Nim version 2.0 using httpbeast fork. Package has been renamed to jesterfork.
Various PR's from original repo has been merged. Dependency on `httpbeast` been changed to `httpbeastfork` to support Nim v2.0.
> Fork of jester for support of Nim v2.x (httpbeastfork) + merged PR's

- packages.json
A fork of httpbeast updated to work with Nim version 2.0 - primarily due to missing nimble/git tags. Package will be working with another fork of jester.
> Fork of httpbeast for Nim v2.x support

- packages.json
Package with access to the essential procedures to create SigV4 presigned urls. 
Based on:
- [sigv4](https://github.com/disruptek/sigv4)
- [depot](https://github.com/guzba/depot)
> Add awsSigV4

- packages.json
Adds some more packages. `xrayAttenuation`, `orgtables` and `flatBuffers` are probably not _that_ interesting to most people (and `orgtables` is ultra limited so far), but given that they are used in the [code](https://github.com/Vindaar/TimepixAnalysis/blob/master/Analysis/ingrid.nimble) of my PhD thesis, I guess allowing to install them directly, seems like a good idea.
> add impulse, xrayAttenuation, orgtables, flatBuffers

- packages.json
A Nim CSS Selectors library for the WHATWG standard compliant Chame HTML parser. Query HTML using CSS selectors with Nim just like you can with JavaScript.
https://github.com/Niminem/CSS3Selectors
> Add package css3selectors

- packages.json
hi nim team,
i would like to publish my first nim package `octolog`. it is a library that built on top of `std/logging` to enable multi-thread logging.
thank you.
> add octolog package

- packages.json
- Stylus is a spec-compliant CSS parser.
- Mirage is a bytecode generator and runtime.
- Ferusgfx is a graphics rendering library for web engines.
Please let me know if I need to split up the PR for the separate packages.
> (add) add stylus, mirage and ferusgfx

- packages.json
The `url` field for the `ferusgfx` package was accidentally pointing to the URL for `mirage`. This PR simply fixes that.
I'm so sorry.
> Fix wrong URL for package ferusgfx

- packages.json
Basic zero-dependency logging with automatic colors and styling.
Detects terminal, respects [`NO_COLOR`](https://no-color.org), extremely simple.
> Add `cozylogwriter` package

- packages.json
This package wraps over std/sysrand and provides functions for fetching commonly-used types of data such as numbers, characters and strings. It also provides a couple of std/random functions (`sample()` and `rand()`)
> Add package rng

- packages.json
i am moving some audio related repos to a new org account nim audio, to hopefully better facilitate collaborative development
> update clap repo url

- packages.json
Norg - a portable wrapper for borg and restic inspired by borgmatic
> Add norg backup

- packages.json
These packages were removed, abandoned or reorganised years ago and should see no usage in the community regardless most of the code was simply moved elsewhere long ago, before the code reached a useful level of quality.
They are unmaintained and probably don't work any more, so keeping them in packages both useless and misleading.
If there was a feature to remove them from the default search function of `nimble.directory`, that could be used in the future for cases like this so as not to break old links.
> clean up status packages

- packages.json
Add the "web" parameter to the "serverly" package in packages.json to add documentation to the package.
> Add documentation to serverly

- packages.json
This PR adds three packages: `louvre`, `gbm` and `shakar`
- `louvre` provides bindings to [Louvre](https://github.com/CuarzoSoftware/Louvre), a library for writing Wayland compositors. Using these bindings, one can write a Wayland compositor in Nim with minimal effort.
- `gbm` provides bindings along with a high-level wrapper to Mesa's GBM (Graphics Buffers Management) API, allowing you to allocate memory (VRAM) on a DRM device of your choice.
- `shakar` provides syntactic sugar features for Nim.
> add: `louvre`, `gbm` and `shakar`

- packages.json
- Nim SDK for Claude Code
- Version 0.0.19 with test coverage
- Repository: https://github.com/Apothic-AI/claude-code-sdk-nim
> Add claude_code_sdk package to registry

- packages.json
The repositories of four packages have migrated to codeberg, and the documentation has been migrated to a custom site. This PR updates the links in packages.json to account for that.
> Update old links

- packages.json
https://github.com/Naitsabot/xkcdgeohashing.nim
Implements Functional and objectoriented APIs for the algorithm from xkcd comic 426, further specified on the geohashing wiki/site
> add xkcdgeohash package

- packages.json
This package provides a fast URL parser based on the WHATWG standard,
and is written in pure Nim. It also includes optional SIMD acceleration
for speedups.
It is mostly a rewrite of [ada-url](https://github.com/ada-url/ada) in Nim, but also draws inspiration from the Rust [url](https://docs.rs/url/latest/url/) crate for its API.
> Add package `url`
